### Send a blog #1

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Bash console",
  "author": "Uri Kiora",
  "url": "http://www.nicecommands.com",
  "likes": 1267
}

### Send a blog #2

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Pepper robot use cases",
  "author": "Haruka Unio",
  "url": "http://www.pepperuses.com",
  "likes": 675
}

### Send an incorrect blog (lacks "likes")

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
   "title": "Rock Civilization - Life of Headhunterz",
   "author": "Headhunterz",
   "url": "https://headhunterz.com"
}

### Get all blogs

GET http://localhost:3001/api/blogs
Accept: application/json

### Delete a blog

DELETE http://localhost:3001/api/blogs/5bf78702023da63ae600f57d
Content-Type: application/json

### Get all users

GET http://localhost:3001/api/users
Accept: application/json

### Add user

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Duukkis",
    "name": "Tuukka",
    "passwordHash": "mamelukkikala",
    "adult": true
}

### Login with correct user credentials

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Duukkis",
    "password": "mamelukkikala"
}

### Login with incorrect user credentials

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Tuukkis",
    "password": "guessingpassword"
}

### Send a blog with a valid token #1

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkR1dWtraXMiLCJpZCI6IjViZmRmMjQ2ZTg4NDFjNWVhNjFhMjE1MCIsImlhdCI6MTU0NDE1MDc3MH0.Ka3WKGvVlJbzX5sTAyPiBIhawFtifz4xZJp44kfwlio

{
    "title": "Bash console",
    "author": "Uri Kiora",
    "url": "http://www.nicecommands.com",
    "likes": 1267
}

### Send a blog with a valid token #2

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkR1dWtraXMiLCJpZCI6IjViZmRmMjQ2ZTg4NDFjNWVhNjFhMjE1MCIsImlhdCI6MTU0NDE1MDc3MH0.Ka3WKGvVlJbzX5sTAyPiBIhawFtifz4xZJp44kfwlio

{
    "title": "Pepper robot use cases",
    "author": "Haruka Unio",
    "url": "http://www.pepperuses.com",
    "likes": 675
}

###